name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧹 Maintenance'
    labels:
      - 'chore'
      - 'dependencies'
  - title: '📚 Documentation'
    labels:
      - 'documentation'
      - 'docs'
  - title: '🧪 Tests'
    labels:
      - 'test'
      - 'testing'
  - title: '🔧 CI/CD'
    labels:
      - 'ci'
      - 'cd'
      - 'workflow'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch

template: |
  ## 🚀 deco Framework v$RESOLVED_VERSION

  ### 📦 What's New
  This release includes the latest improvements and bug fixes for the deco Go framework.

  ### 🔧 Installation
  ```bash
  go install github.com/RodolfoBonis/deco/cmd/decorate-gen@v$RESOLVED_VERSION
  ```

  ### 📋 Changes in this Release

  $CHANGES

  ### 🔗 Links
  - [Documentation](https://github.com/RodolfoBonis/deco/tree/main/docs)
  - [Go Package](https://pkg.go.dev/github.com/RodolfoBonis/deco@v$RESOLVED_VERSION)
  - [Issues](https://github.com/RodolfoBonis/deco/issues)

  ### 📊 Contributors
  $CONTRIBUTORS 