run:
  timeout: 5m
  go: "1.23"

linters:
  enable:
    # Formatação
    - gofmt
    - goimports
    
    # Análise estática básica
    - govet
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    
    # Qualidade de código
    - misspell
    - gosec
    - errcheck
    - gocritic
    - revive
    
    # Performance
    - prealloc
    - wastedassign
    
    # Estilo
    - whitespace
    - gocognit

linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  
  gocognit:
    min-complexity: 30
  
  whitespace:
    multi-if: false
    multi-func: false

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
    - path: "decorators.go"
      linters:
        - revive
      text: "^comment on exported type ParserHook should be of the form"
    - path: "examples/basic/handlers/websocket_handlers.go"
      linters:
        - revive
      text: "^comment on exported function HandleChatMessage should be of the form" 