run:
  timeout: 5m
  go: "1.23"

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell
    - gosec
    - errcheck
    - gocritic
    - revive

linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
    - path: "decorators.go"
      linters:
        - revive
      text: "^comment on exported type ParserHook should be of the form"
    - path: "examples/basic/handlers/websocket_handlers.go"
      linters:
        - revive
      text: "^comment on exported function HandleChatMessage should be of the form" 