version: '3.8'

services:
  # Redis para testes de cache
  redis-test:
    image: redis:7-alpine
    container_name: deco-redis-test
    ports:
      - "6379:6379"
    command: redis-server --appendonly no --save ""
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - deco-test-network

  # OpenTelemetry Collector para testes de telemetria
  otel-collector-test:
    image: otel/opentelemetry-collector:latest
    container_name: deco-otel-test
    ports:
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
      - "8888:8888"   # Prometheus metrics
      - "8889:8889"   # Prometheus metrics (legacy)
    volumes:
      - ./test/otel-config.yaml:/etc/otelcol/config.yaml
    command: ["--config", "/etc/otelcol/config.yaml"]
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:13133"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - deco-test-network

networks:
  deco-test-network:
    driver: bridge 